-- Final subcategories for categories 12-20

INSERT INTO "subcategories" (id, name, slug, "categoryId", "order", "isActive", "createdAt", "updatedAt") VALUES

-- Sauces & Spreads subcategories
('sub-tomato-chilli-ketchup', 'Tomato & Chilli Ketchup', 'tomato-chilli-ketchup', 'cat-sauces-spreads', 1, true, NOW(), NOW()),
('sub-asian-sauces', 'Asian Sauces', 'asian-sauces', 'cat-sauces-spreads', 2, true, NOW(), NOW()),
('sub-mayonnaise', 'Mayonnaise', 'mayonnaise', 'cat-sauces-spreads', 3, true, NOW(), NOW()),
('sub-peanut-butter-sauces', 'Peanut Butter', 'peanut-butter-sauces', 'cat-sauces-spreads', 4, true, NOW(), NOW()),
('sub-jam-spreads', 'Jam & Spreads', 'jam-spreads', 'cat-sauces-spreads', 5, true, NOW(), NOW()),
('sub-honey-chyawanprash-sauces', 'Honey & Chyawanprash', 'honey-chyawanprash-sauces', 'cat-sauces-spreads', 6, true, NOW(), NOW()),
('sub-syrups-sauces', 'Syrups', 'syrups-sauces', 'cat-sauces-spreads', 7, true, NOW(), NOW()),
('sub-indian-chutney-pickle', 'Indian Chutney & Pickle', 'indian-chutney-pickle', 'cat-sauces-spreads', 8, true, NOW(), NOW()),
('sub-dips-salad-dressings', 'Dips & Salad Dressings', 'dips-salad-dressings', 'cat-sauces-spreads', 9, true, NOW(), NOW()),
('sub-table-sauces', 'Table Sauces', 'table-sauces', 'cat-sauces-spreads', 10, true, NOW(), NOW()),
('sub-cooking-sauces-vinegar', 'Cooking Sauces & Vinegar', 'cooking-sauces-vinegar', 'cat-sauces-spreads', 11, true, NOW(), NOW()),
('sub-imported-spreads', 'Imported Spreads', 'imported-spreads', 'cat-sauces-spreads', 12, true, NOW(), NOW()),

-- Chicken, Meat & Fish subcategories
('sub-fresh-meat', 'Fresh Meat', 'fresh-meat', 'cat-chicken-meat-fish', 1, true, NOW(), NOW()),
('sub-eggs-meat', 'Eggs', 'eggs-meat', 'cat-chicken-meat-fish', 2, true, NOW(), NOW()),
('sub-frozen-non-veg-snacks-meat', 'Frozen Non Veg Snacks', 'frozen-non-veg-snacks-meat', 'cat-chicken-meat-fish', 3, true, NOW(), NOW()),
('sub-chicken', 'Chicken', 'chicken', 'cat-chicken-meat-fish', 4, true, NOW(), NOW()),
('sub-mutton', 'Mutton', 'mutton', 'cat-chicken-meat-fish', 5, true, NOW(), NOW()),
('sub-fish-seafood', 'Fish & Seafood', 'fish-seafood', 'cat-chicken-meat-fish', 6, true, NOW(), NOW()),
('sub-sausages-salami-ham-meat', 'Sausages, Salami & Ham', 'sausages-salami-ham-meat', 'cat-chicken-meat-fish', 7, true, NOW(), NOW()),
('sub-exotic-meat', 'Exotic Meat', 'exotic-meat', 'cat-chicken-meat-fish', 8, true, NOW(), NOW()),

-- Organic & Healthy Living subcategories
('sub-oil-ghee-organic', 'Oil & Ghee', 'oil-ghee-organic', 'cat-organic-healthy', 1, true, NOW(), NOW()),
('sub-flour-organic', 'Flour', 'flour-organic', 'cat-organic-healthy', 2, true, NOW(), NOW()),
('sub-noodles-pasta-organic', 'Noodles & Pasta', 'noodles-pasta-organic', 'cat-organic-healthy', 3, true, NOW(), NOW()),
('sub-dry-fruits-seeds-organic', 'Dry Fruits & Seeds', 'dry-fruits-seeds-organic', 'cat-organic-healthy', 4, true, NOW(), NOW()),
('sub-pulses-millets', 'Pulses & Millets', 'pulses-millets', 'cat-organic-healthy', 5, true, NOW(), NOW()),
('sub-premium-sauces-spreads', 'Premium Sauces & Spreads', 'premium-sauces-spreads', 'cat-organic-healthy', 6, true, NOW(), NOW()),
('sub-spices-vinegar-organic', 'Spices & Vinegar', 'spices-vinegar-organic', 'cat-organic-healthy', 7, true, NOW(), NOW()),
('sub-organic-salt-sugar-honey', 'Organic Salt, Sugar & Honey', 'organic-salt-sugar-honey', 'cat-organic-healthy', 8, true, NOW(), NOW()),
('sub-chocolate-candies-organic', 'Chocolate & Candies', 'chocolate-candies-organic', 'cat-organic-healthy', 9, true, NOW(), NOW()),
('sub-rice-rice-products', 'Rice & Rice Products', 'rice-rice-products', 'cat-organic-healthy', 10, true, NOW(), NOW()),
('sub-cookies-wafers-organic', 'Cookies & Wafers', 'cookies-wafers-organic', 'cat-organic-healthy', 11, true, NOW(), NOW()),
('sub-tea-coffee-organic', 'Tea & Coffee', 'tea-coffee-organic', 'cat-organic-healthy', 12, true, NOW(), NOW()),

-- Baby Care subcategories
('sub-diapers-more', 'Diapers & More', 'diapers-more', 'cat-baby-care', 1, true, NOW(), NOW()),
('sub-bathing-needs', 'Bathing Needs', 'bathing-needs', 'cat-baby-care', 2, true, NOW(), NOW()),
('sub-baby-wipes', 'Baby Wipes', 'baby-wipes', 'cat-baby-care', 3, true, NOW(), NOW()),
('sub-baby-food', 'Baby Food', 'baby-food', 'cat-baby-care', 4, true, NOW(), NOW()),
('sub-skin-hair-care-baby', 'Skin & Hair Care', 'skin-hair-care-baby', 'cat-baby-care', 5, true, NOW(), NOW()),
('sub-feeding-essentials', 'Feeding Essentials', 'feeding-essentials', 'cat-baby-care', 6, true, NOW(), NOW()),
('sub-oral-nasal-care', 'Oral & Nasal Care', 'oral-nasal-care', 'cat-baby-care', 7, true, NOW(), NOW()),
('sub-nursing', 'Nursing', 'nursing', 'cat-baby-care', 8, true, NOW(), NOW()),
('sub-baby-gifting-toys', 'Baby Gifting & Toys', 'baby-gifting-toys', 'cat-baby-care', 9, true, NOW(), NOW()),
('sub-hygiene-baby', 'Hygiene', 'hygiene-baby', 'cat-baby-care', 10, true, NOW(), NOW()),
('sub-mom-care-needs', 'Mom Care Needs', 'mom-care-needs', 'cat-baby-care', 11, true, NOW(), NOW()),
('sub-health-safety', 'Health & Safety', 'health-safety', 'cat-baby-care', 12, true, NOW(), NOW()),
('sub-baby-accessories', 'Baby Accessories', 'baby-accessories', 'cat-baby-care', 13, true, NOW(), NOW()),
('sub-baby-gear', 'Baby Gear', 'baby-gear', 'cat-baby-care', 14, true, NOW(), NOW()),

-- Pharma & Wellness subcategories
('sub-sexual-wellness', 'Sexual Wellness', 'sexual-wellness', 'cat-pharma-wellness', 1, true, NOW(), NOW()),
('sub-adult-diapers', 'Adult Diapers', 'adult-diapers', 'cat-pharma-wellness', 2, true, NOW(), NOW()),
('sub-health-wellness-supplements', 'Health & Wellness Supplements', 'health-wellness-supplements', 'cat-pharma-wellness', 3, true, NOW(), NOW()),
('sub-protein-workout-supplements', 'Protein and Workout Supplements', 'protein-workout-supplements', 'cat-pharma-wellness', 4, true, NOW(), NOW()),
('sub-masks-sanitizers', 'Masks & Sanitizers', 'masks-sanitizers', 'cat-pharma-wellness', 5, true, NOW(), NOW()),
('sub-milk-drinks-pharma', 'Milk Drinks', 'milk-drinks-pharma', 'cat-pharma-wellness', 6, true, NOW(), NOW()),
('sub-smoking-cessation-pharma', 'Smoking Cessation', 'smoking-cessation-pharma', 'cat-pharma-wellness', 7, true, NOW(), NOW()),
('sub-herbal-drinks-pharma', 'Herbal Drinks', 'herbal-drinks-pharma', 'cat-pharma-wellness', 8, true, NOW(), NOW()),
('sub-chyawanprash-pharma', 'Chyawanprash', 'chyawanprash-pharma', 'cat-pharma-wellness', 9, true, NOW(), NOW()),
('sub-health-ortho-supports', 'Health & Ortho Supports', 'health-ortho-supports', 'cat-pharma-wellness', 10, true, NOW(), NOW()),
('sub-pure-otc', 'Pure OTC', 'pure-otc', 'cat-pharma-wellness', 11, true, NOW(), NOW()),
('sub-hangover-cure', 'Hangover Cure', 'hangover-cure', 'cat-pharma-wellness', 12, true, NOW(), NOW()),

-- Cleaning Essentials subcategories
('sub-fabric-conditioners-additive', 'Fabric Conditioners & Additive', 'fabric-conditioners-additive', 'cat-cleaning-essentials', 1, true, NOW(), NOW()),
('sub-floor-surface-cleaners', 'Floor & Surface Cleaners', 'floor-surface-cleaners', 'cat-cleaning-essentials', 2, true, NOW(), NOW()),
('sub-toilet-bathroom-cleaners', 'Toilet & Bathroom Cleaners', 'toilet-bathroom-cleaners', 'cat-cleaning-essentials', 3, true, NOW(), NOW()),
('sub-fresheners', 'Fresheners', 'fresheners', 'cat-cleaning-essentials', 4, true, NOW(), NOW()),
('sub-detergent-powder-bars', 'Detergent Powder & Bars', 'detergent-powder-bars', 'cat-cleaning-essentials', 5, true, NOW(), NOW()),
('sub-dishwashing-gels-tablets', 'Dishwashing Gels & Tablets', 'dishwashing-gels-tablets', 'cat-cleaning-essentials', 6, true, NOW(), NOW()),
('sub-cleaning-tools', 'Cleaning Tools', 'cleaning-tools', 'cat-cleaning-essentials', 7, true, NOW(), NOW()),
('sub-dishwashing-bars-tubs', 'Dishwashing Bars & Tubs', 'dishwashing-bars-tubs', 'cat-cleaning-essentials', 8, true, NOW(), NOW()),
('sub-disinfectants', 'Disinfectants', 'disinfectants', 'cat-cleaning-essentials', 9, true, NOW(), NOW()),
('sub-dishwashing-accessories', 'Dishwashing Accessories', 'dishwashing-accessories', 'cat-cleaning-essentials', 10, true, NOW(), NOW()),
('sub-shoe-care', 'Shoe Care', 'shoe-care', 'cat-cleaning-essentials', 11, true, NOW(), NOW()),
('sub-garbage-bags', 'Garbage Bags', 'garbage-bags', 'cat-cleaning-essentials', 12, true, NOW(), NOW()),
('sub-liquid-detergents', 'Liquid Detergents', 'liquid-detergents', 'cat-cleaning-essentials', 13, true, NOW(), NOW()),
('sub-repellents', 'Repellents', 'repellents', 'cat-cleaning-essentials', 14, true, NOW(), NOW()),

-- Home & Office subcategories
('sub-pooja-needs', 'Pooja Needs', 'pooja-needs', 'cat-home-office', 1, true, NOW(), NOW()),
('sub-party-essentials', 'Party Essentials', 'party-essentials', 'cat-home-office', 2, true, NOW(), NOW()),
('sub-home-decor', 'Home Décor', 'home-decor', 'cat-home-office', 3, true, NOW(), NOW()),
('sub-festive-occasion-needs', 'Festive & Occasion Needs', 'festive-occasion-needs', 'cat-home-office', 4, true, NOW(), NOW()),
('sub-tissues-disposables', 'Tissues & Disposables', 'tissues-disposables', 'cat-home-office', 5, true, NOW(), NOW()),
('sub-bathroom-essentials', 'Bathroom Essentials', 'bathroom-essentials', 'cat-home-office', 6, true, NOW(), NOW()),
('sub-sports-fitness', 'Sports & Fitness', 'sports-fitness', 'cat-home-office', 7, true, NOW(), NOW()),
('sub-car-bike-care', 'Car & Bike Care', 'car-bike-care', 'cat-home-office', 8, true, NOW(), NOW()),
('sub-home-improvement', 'Home Improvement', 'home-improvement', 'cat-home-office', 9, true, NOW(), NOW()),
('sub-flowers-plants-gardening', 'Flowers, Plants & Gardening', 'flowers-plants-gardening', 'cat-home-office', 10, true, NOW(), NOW()),
('sub-forex-cards', 'Forex Cards', 'forex-cards', 'cat-home-office', 11, true, NOW(), NOW()),
('sub-home-furnishing', 'Home Furnishing', 'home-furnishing', 'cat-home-office', 12, true, NOW(), NOW()),

-- Personal Care subcategories
('sub-face-body-moisturizer', 'Face & Body Moisturizer', 'face-body-moisturizer', 'cat-personal-care', 1, true, NOW(), NOW()),
('sub-bath-beauty-gifts', 'Bath & Beauty Gifts', 'bath-beauty-gifts', 'cat-personal-care', 2, true, NOW(), NOW()),
('sub-feminine-care', 'Feminine Care', 'feminine-care', 'cat-personal-care', 3, true, NOW(), NOW()),
('sub-oral-care', 'Oral Care', 'oral-care', 'cat-personal-care', 4, true, NOW(), NOW()),
('sub-handwash', 'Handwash', 'handwash', 'cat-personal-care', 5, true, NOW(), NOW()),
('sub-face-cleaning', 'Face Cleaning', 'face-cleaning', 'cat-personal-care', 6, true, NOW(), NOW()),
('sub-mens-grooming', 'Mens Grooming', 'mens-grooming', 'cat-personal-care', 7, true, NOW(), NOW()),
('sub-sunscreen', 'Sunscreen', 'sunscreen', 'cat-personal-care', 8, true, NOW(), NOW()),
('sub-hair-care', 'Hair Care', 'hair-care', 'cat-personal-care', 9, true, NOW(), NOW()),
('sub-deodorant-talc', 'Deodorant & Talc', 'deodorant-talc', 'cat-personal-care', 10, true, NOW(), NOW()),
('sub-womens-grooming', 'Womens Grooming', 'womens-grooming', 'cat-personal-care', 11, true, NOW(), NOW()),
('sub-skin-hair-care-personal', 'Skin & Hair Care', 'skin-hair-care-personal', 'cat-personal-care', 12, true, NOW(), NOW()),
('sub-face-wash', 'Face Wash', 'face-wash', 'cat-personal-care', 13, true, NOW(), NOW()),
('sub-bathing-soaps', 'Bathing Soaps', 'bathing-soaps', 'cat-personal-care', 14, true, NOW(), NOW()),
('sub-face-moisturiser', 'Face Moisturiser', 'face-moisturiser', 'cat-personal-care', 15, true, NOW(), NOW()),
('sub-shower-gels-body-wash', 'Shower Gels & Body Wash', 'shower-gels-body-wash', 'cat-personal-care', 16, true, NOW(), NOW()),
('sub-bathing', 'Bathing', 'bathing', 'cat-personal-care', 17, true, NOW(), NOW()),

-- Pet Care subcategories
('sub-accessories-other-supplies', 'Accessories & Other Supplies', 'accessories-other-supplies', 'cat-pet-care', 1, true, NOW(), NOW()),
('sub-cat-needs', 'Cat Needs', 'cat-needs', 'cat-pet-care', 2, true, NOW(), NOW()),
('sub-diverse-pet-food', 'Diverse Pet Food', 'diverse-pet-food', 'cat-pet-care', 3, true, NOW(), NOW()),
('sub-dogs-needs', 'Dogs Needs', 'dogs-needs', 'cat-pet-care', 4, true, NOW(), NOW()),
('sub-pet-grooming', 'Pet Grooming', 'pet-grooming', 'cat-pet-care', 5, true, NOW(), NOW());
